FROM node:lts-alpine as builder

RUN mkdir -p /usr/src/app && chown node:node /usr/src/app

RUN npm install -g npm@latest

USER node

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node .npmrc ./

RUN npm ci

COPY --chown=node:node . ./

CMD ["npm", "run", "build"]
