FROM node:lts-alpine as builder

ARG HOST_TYPE=local

ENV HOST_TYPE=$HOST_TYPE

RUN mkdir -p /usr/src/app && chown node:node /usr/src/app

RUN npm install -g npm@latest

USER node

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node .npmrc ./

RUN npm ci

COPY --chown=node:node . ./

RUN npm run build

FROM nginx:stable-alpine

RUN mkdir -p /var/www/localhost && \
  mkdir -p /var/run/nginx && \
  chown -R nobody:nobody /var/log/nginx /var/cache/nginx /etc/nginx /var/run/nginx /var/www/localhost

COPY --from=builder --chown=nobody:nobody /usr/src/app/dist /var/www/localhost

COPY --chown=nobody:nobody nginx/localhost.conf /etc/nginx/conf.d/localhost.conf

COPY --chown=nobody:nobody nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

USER nobody

CMD [ "nginx", "-g", "daemon off;" ]
