#!/bin/bash

# Build assets

npm run build

# Get results breakdown URL

BUNDLEWATH_RESULT="$(npx bundlewatch --config bundlewatch.config.json | awk '/^Result breakdown at:/ { print $4 }')";

# Replace existing URL with the new one

sed -i "s|^\[Bundle size\].*|[Bundle size]($BUNDLEWATH_RESULT)|" README.md;

# Stage and commit README.md

git add README.md && git commit -m "Update README.md with bundlewatch results URL";
