#!/bin/bash

# Remove previous results

rm -rf sitespeed-result

# Get Sitespeed.io (https://www.sitespeed.io/) performance results

docker run \
  --rm \
  -v "$(pwd):/sitespeed.io" \
  --network=host \
  sitespeedio/sitespeed.io:16.8.1 \
  --outputFolder sitespeed-result \
  https://credit-report-web-container-poc.dev.ctmers.io:3000

# Push results to S3 bucket

aws s3 sync sitespeed-result s3://credit-report-s3-poc.test.ctmers.io/sitespeed-result/custom-micro-frontend
