#!/bin/bash

TETS_URL=$1
S3_FOLDER=$2

# Remove previous results

rm -rf sitespeed-result

# Get Sitespeed.io (https://www.sitespeed.io/) performance results

docker run \
  --rm \
  -v "$(pwd):/sitespeed.io" \
  --network=host \
  sitespeedio/sitespeed.io:16.9.2-plus1 \
  --outputFolder sitespeed-result \
  --plugins.remove /gpsi \
  $TETS_URL

# Push results to S3 bucket

aws s3 sync sitespeed-result s3://credit-report-s3-poc.test.ctmers.io/sitespeed-result/custom-micro-frontend/$S3_FOLDER
